### ISSUE TITLE
spring wheat code

### ISSUE THREAD

**Issue by Martincccc** [maja601/EuroCrops#13] opened 2022-09-23 14:51 UTC
Hi @maja601 

I figured spring wheat can named differently in two countries (just looked at FR and NL)

FR | 3301010102 | spring_common_soft_wheat
NL | 3301010103 | summer_common_soft_wheat

Is this intentional to highlight a difference ? or this should be merged ?

Thanks

Martin

**Comment by sbgeophd** [comment] 2022-09-23 16:27
These are the same thing. You'll see spring and summer variously used in different countries but they are the same.

**Comment by maja601** [comment] 2022-09-28 07:36
Hi @Martincccc and @sbgeophd!
Yes thank you for putting this issue here; it's actually one of the biggest discussions we had while constructing EuroCrops. The problem is that it seems like there is no clear answer to that and that some experts say that it's the same, whereas others bring forward that in different regions there is actually a difference between them. 
We only had summer in our first iteration of HCAT, but then changed it over time as I am certainly not qualified to make this decision which one to keep ;)
However, It seems like (regarding NL) we missed to update some mappings which we should change (I think Martin already took care of that) but apart from that I would suggest leaving it with the direct translations for now, it a later iteration the two classes can always be merged.

**Comment by sbgeophd** [comment] 2022-09-28 10:52
There are indeed agronomic regions where there is a distinction between summer and spring cereals.

However...

None of the EU datasets in EuroCrops contain both spring and summer (soft) wheat. They all either use spring or summer. None are actually making the distinction which occasionally does exist. They are different only linguistically. Spring wheat in France is referring to the same thing as summer wheat in the Netherlands.
For any cross-country work using EuroCrops, these categories should be merged. For any single country work, there isn't any distinction anyway. Therefore I'd suggest to merge them back and call them all "spring wheat" as that is the usual English nomenclature.

**Comment by maja601** [comment] 2022-09-28 11:54
Ah, okay that is actually super interesting to know! So in our (European) case, spring and summer (soft) wheat are **always** sown and harvested at approximately the same time and they are also the same type of plant?
Then I agree and would say that for HCATv2 (the current version) we just translate it to plain English and in HCATv3 we merge summer and spring cereals.

**Closed** 2023-04-21 14:10 UTC
